name: Public Release Creation

on: 
  push:
    branches:
      - public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    # Get the version from 'module.json'
    - name: Get Version
      shell: bash
      id: get-version
      run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        manifest: https://github.com/${{github.repository}}-Public/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}-Public/releases/download/${{ steps.get-version.outputs.version }}/module.zip

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ./module.zip module.json styles/ vino.js scripts/ templates/ apps/ languages/


    # Create a release for this specific version
    - name: Create Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: Release ${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./module.zip'
        tag: ${{ steps.get-version.outputs.version }}
